name: ztdl-gpu
channels:
- defaults
dependencies:
- python=3.5
- pip==9.0.1
- numpy==1.13.1
- jupyter==1.0
- matplotlib==2.0.2
- scikit-learn==0.18.2
- scipy==0.19.1
- pandas==0.20.3
- pillow==4.2.1
- seaborn==0.8
- h5py==2.7.0
- pytest==3.1.3
- pip:
  - tensorflow-gpu==1.3.0
  - keras==2.0.6
